version: "3.1"

services:
    mariadb1:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: "root_password"
            MYSQL_DATABASE: "mydb"
            MYSQL_USER: "cluster_user"
            MYSQL_PASSWORD: "clusterpass"
        ports:
            - "3306:3306"
        expose:
            - 4444
            - 4567
            - 4568
        networks:
            - overlay    
        volumes:
            - ./db-mariadb1-data:/var/lib/mysql:rw
            - ./db-mariadb1-log:/var/log:rw
            - ./configs/mariadb1.cnf:/etc/mysql/my.cnf
        command: mysqld --wsrep-new-cluster
    mariadb2:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: "root_password"
            MYSQL_DATABASE: "mydb"
            MYSQL_USER: "cluster_user"
            MYSQL_PASSWORD: "clusterpass"
        ports:
            - "3316:3306"
        expose:
            - 4444
            - 4567
            - 4568
        networks:
            - overlay
        volumes:
            - ./db-mariadb2-data:/var/lib/mysql:rw
            - ./db-mariadb2-log:/var/log:rw
            - ./configs/mariadb2.cnf:/etc/mysql/my.cnf
    mariadb3:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: "root_password"
            MYSQL_DATABASE: "mydb"
            MYSQL_USER: "cluster_user"
            MYSQL_PASSWORD: "clusterpass"
        ports:
            - "3326:3306"
        expose:
            - 4444
            - 4567
            - 4568
        networks:
            - overlay
        volumes:
            - ./db-mariadb3-data:/var/lib/mysql:rw
            - ./db-mariadb3-log:/var/log:rw
            - ./configs/mariadb3.cnf:/etc/mysql/my.cnf

networks:
    overlay: