version: "3.1"

services:
    master1: 
        image: mariadb:10.3.22
        restart: always
        networks: 
            - replicanet
        hostname: master1
        volumes:
            - ./db-master1-data:/var/lib/mysql:rw
            - ./db-master1-log:/var/log/mysql/:rw
            - ./configs/master1.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: "master1secret"
            
    master2: 
        image: mariadb:10.3.22
        restart: always
        networks: 
            - replicanet
        hostname: master2
        volumes:
            - ./db-master2-data:/var/lib/mysql:rw
            - ./db-master2-log:/var/log/mysql/:rw
            - ./configs/master2.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: "master2secret"


networks:
    replicanet: